name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-10.14
    env:
      COMMIT_SHA8: ${GITHUB_SHA::8}
    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      run: git submodule update --init
    - name: build
      run: |
        xcodebuild -scheme VoodooSMBus build CONFIGURATION_BUILD_DIR=/tmp/VoodooSMBus-${COMMIT_SHA8}
        mv /tmp/VoodooSMBus-${COMMIT_SHA8}/VoodooSMBus.kext /tmp/VoodooSMBus-${COMMIT_SHA8}/VoodooSMBus-${COMMIT_SHA8}.kext
    - uses: actions/upload-artifact@v2
      with:
        name: VoodooSMBus-${COMMIT_SHA8}.kext
        path: /tmp/VoodooSMBus-${COMMIT_SHA8}
  
