name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      run: git submodule update --init
    - name: get shortsha
      id: vars
      run: |
        echo ::set-output name=sha_short::$(git rev-parse --short=8 ${{ github.sha }})
    - name: build
      env: 
          VOODOOSMBUS_SHA: VoodooSMBus-${{ steps.vars.outputs.sha_short }}
      run: |
        xcodebuild -scheme VoodooSMBus build CONFIGURATION_BUILD_DIR=/tmp/${VOODOOSMBUS_SHA}
        mv /tmp/${VOODOOSMBUS_SHA}/VoodooSMBus.kext /tmp/${VOODOOSMBUS_SHA}/${VOODOOSMBUS_SHA}.kext
    - uses: actions/upload-artifact@v2
      with:
        name: VoodooSMBus
        path: /tmp/VoodooSMBus-*
  
