name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-10.14
    
    steps:
    - uses: textbook/git-checkout-submodule-action@master
    - name: build
      run: xcodebuild -scheme VoodooSMBus build
