name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-10.14
    
    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      run: git submodule update --init
    - name: build
      run: xcodebuild -scheme VoodooSMBus build
    - uses: actions/upload-artifact@v2
      with:
        name: VoodooSMBus.kext
        path: /Users/runner/Library/Developer/Xcode/DerivedData/VoodooSMBus-*/Build/Products/Debug/VoodooSMBus.kext
  
